CREATE TABLE IF NOT EXISTS events (
    api_id                     TEXT PRIMARY KEY,
    name                       TEXT NOT NULL,
    url_slug                   TEXT,
    starts_at                  TIMESTAMPTZ,
    ends_at                    TIMESTAMPTZ,
    is_online                  BOOLEAN NOT NULL,
    host_name                  TEXT,
    city                       TEXT,
    region                     TEXT,
    sublocality                TEXT,
    country_code               TEXT,
    latitude                   DOUBLE PRECISION,
    longitude                  DOUBLE PRECISION,
    is_free                    BOOLEAN,
    price_cents                INTEGER,
    require_approval           BOOLEAN,
    waitlist_status            TEXT,
    registration_availability  TEXT,
    calendar_access_level      TEXT,
    discovered_via             TEXT,
    category                   TEXT NOT NULL,
    rsvp_type                  TEXT NOT NULL,
    first_seen_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
